const ROUTES = {
  SPLASH: 'splash',
  AUTHNAVIGATOR: 'authNavigator',
  WELCOME: 'welcome',
  SIGNUP: 'signUp',
  LOGIN: 'login',
  HOME: 'home',
  FORGOTPASSWORD: 'forgotPassword',
  VERIFYCODE: 'verifyCode',
  SETPASSWORD: 'setPassword',
  REPORTS: 'reports',
  CONTRACTORS: 'contractors',
  NOTIFICATIONS: 'notifications',
  PROFILE: 'profile',
  BOTTOMTAB: 'bottomTab',
  ADDREPORTS: 'addReports',
  PROCESSREPORT: 'processReports',
  UNREAD: 'Unread',
  READ: 'Read',
  CONTRACTORSDETAILS: 'contractorDetails',
  PASSWORDSCREEN: 'password',
  PROFILENAVIGATOR: 'profileNavigator',
};

export default ROUTES;
