export const CommonStrings = {
  pleaseEnterOtp: 'Please enter the OTP',
  pleaseEnterEmail: '*Please enter an email',
  pleaseEnterFirstName: '*Please enter a first name',
  pleaseEnterLastName: '*Please enter a last name',
  pleaseEnterAnEmail: '*Please enter an email address',
  pleaseEnterPassword: '*Please enter your password to continue',
  pleaseEnterValidEmail: '*Please enter a valid email address',
  pleaseEnterValidFirstName: '*Please enter a valid first name',
  pleaseEnterValidLastName: '*Please enter a valid last name',
  pleaseEnterMobile: 'Please enter your mobile number',
  pleaseEnterValidPassword: '*Please enter a valid password',
  pleaseEnterConfirmPassword: '*Please enter confirm password',
  pleaseEnterValidMobile: 'Please enter a valid mobile number',
  pleaseEnterValidCred: 'Please enter a valid username or email',
  pleaseEnterUserNameEmail: 'Please enter your username or email',
  pleaseEnterYourPassword: '*Please enter your password to continue',
  pleaseEnterYourEmail: '*Please enter your email to continue',
  pleaseCheckYourEntry: '*Please check your entry and try again',
  pleaseCheckYourEmailAndPassword:
    '*Please check your email and password, then try again',
  pleaseEnterYourEmailToResetPassword:
    '*Please enter your email address to reset your password',
  pleaseCheckYourEntryMustBeValidEmail:
    '*Please check your entry, it must be a valid email address',
  passwordsMustMatch: '*Passwords must match',
  WelcomeToInspectReplyAI: 'Welcome to InspectReply-AI!',
  welcomeDescription:
    'Transform your home inspection experience with instant AI-powered insights, repair cost estimates, and local contractor recommendations at your fingertips.',
  getStarted: 'Get Started',
  signIn: 'Sign In',
  signUp: 'Sign Up',
  firstName: 'First name',
  lastName: 'Last name',
  email: 'Email',
  emailExample: 'write@yourmail.com',
  password: 'Password',
  confirmPassword: 'Confirm password',
  iaccept: 'I accept the ',
  termsAndConditions: 'Terms and Conditions ',
  privacyPolicy: ' Privacy Policy',
  Continue: 'Continue',
  alreadyAccount: 'Already have an account? ',
  forgotPassword: 'Forgot password',
  next: 'Next',
  dontHaveAccount: 'Don’t have an account? ',
  registerHere: 'Register here! ',
  resetPassword: 'Reset Password',
  verifyCode: 'Verification code',
  enterVerificationCode: 'Verification Code',
  resendCode: 'Resend Code',
  checkEmailForVerification:
    'Please check your email for the verification code',
  enterVerificationCodeToReset:
    'Please enter your verification code to reset your password',
  codeIsInvalid: 'Code is invalid',
  welcomeBack: 'Welcome back',
  welComeBackDescription:
    'Welcome back to InspectReply-AI! Dive back into seamless home inspections with instant insights, accurate cost estimates, and top local contractors ready to help.',
  searchReports: 'Search reports',
  dateCreated: 'Date Created: ',
  totalRepairCost: 'Total Repair Cost: ',
  lastShared: 'Last Shared: ',
  viewFullReport: 'View Full Report',
  noReports: 'No Reports',
  emptyContent: 'Click the + button to add your first report.',
  uploadFile: 'Select here to upload file',
  uploadPdf: 'Click to upload a PDF file.',
  reportGenerated:
    '...and when your report is generated they can be pre-populated.',
  generateReport: 'Generate Report',
  preferredContractor: 'Add Preferred Contractors',
  addReport: 'Add report',
  useContractor: 'Use preferred contractors',
  noteWhenSelected:
    'Note: when selected, this will pull from your top contractors list.',
  needChangePdfNote:
    'Need to make a change? Remove the current report and upload a new one.',
  reportPdfText1:
    'Your report is being generated and may take up to 10 minutes to compile. ',
  reportPdfText2:
    'You will receive a notification once the report is complete.',
  coachMarkText1:
    'This is the report section where you can view all your recent, saved, and shared reports.',
  coachMarkText2: 'Click this to upload a report.',
  coachMarkText3: 'This is the Contractor Section. About this section.',
  gotIt: 'Got it',
  acceptTermsAndConditions:
    '*Terms and Conditions must be accepted to continue',
  editReport: 'Edit Report',
  shareReport: 'Share Report',
  saveReport: 'Save Report',
  Error: 'Error',
  Success: 'Success',
  myProfile: 'My Profile',
  deleteProfile: 'Delete Profile',
  deleteProfileDesc: 'Are you sure you want to delete your profile?',
  deleteContractorText:
    'Are you sure you want to delete your preferred contractor?',
  confirm: 'Confirm',
  delete: 'Delete',
  cancel: 'Cancel',
  name: 'Name',
  terms: 'Terms',
  privacy: 'Privacy',
  notifications: 'Notifications',
  pleaseEnterName: '*Please enter your name',
  imageIsTooBig: 'Image is too big. Max file size is upto 5 MB.',
  cameraAccessDenied: 'Access Denied Camera',
  galleryAccessDenied: 'Access Denied Gallery',
  alertTitle: 'Alert Title',
  fileSizeTooBig: 'File size to big',
  goToSetting: 'Go To Settings',
  permissionNotGranted: 'Permission not granted',
  permissionBlocked: 'Permissions Blocked',
  contractors: 'Contractors',
  company: 'Company',
  companyName: 'Company Name',
  contractorName: 'Contractor Name',
  phone: 'Phone',
  address1: 'Address Line 1',
  address2: 'Address Line 2',
  city: 'City',
  state: 'State',
  zip: 'ZIP',
  website: 'Website (optional)',
  deleteContractor: 'Delete Contractor',
  category: 'Category',
  logout: 'Logout',
  save: 'SAVE',
  selectCategory: 'Select a Category',
  selectCity: 'Select City',
  selectState: 'Select State',
  companyRequired: '*Please enter a company name',
  contractorNameRequired: '*Please enter a contractor name',
  invalidEmail: '*Invalid email format',
  emailRequired: '*Please enter an email address',
  phoneNumberMustBe: 'Phone number must be at least 10 digits',
  phoneNumberRequired: '*Please enter a phone number',
  addressRequired: '*Please enter an address',
  zipRequired: '*Please enter a ZIP code',
  noCategoryAdded: 'No Category Added',
  noStates: 'No States Added',
  noCity: 'No City Added',
  search: 'Search',
  noContractorFound: 'No Contractor Found',
  selectCityFirst: '*Please select state first',
  selectImageSource: 'Select Image Source',
  choosefromGalleryOrCamera: 'Choose from gallery or camera',
  camera: 'Camera',
  gallery: 'Gallery',
  largeFile: 'File size to big',
  contractorname: 'contractorName',
  addressOne: 'address1',
  addressTwo: 'address2',
  web: 'website',
  changePassword: 'Change Password',
  oldPassword: 'Old Password',
  newPassword: 'New Password',
  confirmChanges: 'Confirm Changes',
  passwordCannotBeSame:
    'Old and new password cannot be same. \nPlease choose a unique password.',
  requirements: '  Requirements:',
  newContractor: 'Add a Contractor',
  passwordMeetsCriteria:
    '*Please make sure the password meets all of the criteria below',
  atLeast8Characters: 'At least 8 characters',
  uppercaseLetter: 'Uppercase letter',
  lowerCaseLetter: 'Lowercase letter',
  number: 'Number',
  setNewPassword: 'Set New Password',
  searchContractor: 'Search contractors',
  connectionError: 'Connection Error',
  retry: 'Retry',
  largeFileSize: 'File Size is Too Large',
  selectPdfFile: 'Please select a PDF File',
  reports: 'Reports',
  recent: 'Recent',
  shared: 'Shared',
  saved: 'Saved',
  purchaseFullReport: 'Purchase Full Report',
};
