export const CommonStrings = {
  pleaseEnterOtp: 'Please enter the OTP',
  pleaseEnterEmail: '*Please enter an email',
  pleaseEnterFirstName: '*Please enter an first name',
  pleaseEnterLastName: '*Please enter an last name',

  pleaseEnterPassword: '*Please enter your password to continue',
  pleaseEnterValidEmail: '*Please enter a valid email address',
  pleaseEnterValidFirstName: '*Please enter a valid first name',
  pleaseEnterValidLastName: '*Please enter a valid last name',
  pleaseEnterMobile: 'Please enter your mobile number',
  pleaseEnterValidPassword: '*Please enter a valid password',
  pleaseEnterConfirmPassword: '*Please enter confirm password',
  pleaseEnterValidMobile: 'Please enter a valid mobile number',
  pleaseEnterValidCred: 'Please enter a valid username or email',
  pleaseEnterUserNameEmail: 'Please enter your username or email',
  passwordsMustMatch: '*Passwords must match',
  WelcomeToInspectReplyAI: 'Welcome to InspectReply-AI!',
  welcomeDescription:
    'Transform your home inspection experience with instant AI-powered insights, repair cost estimates, and local contractor recommendations at your fingertips.',
  getStarted: 'Get Started',
  signIn: 'Sign In',
  signUp: 'Sign up',
  firstName: 'First name',
  lastName: 'Last name',
  email: 'Email',
  emailExample: 'write@yourmail.com',
  password: 'Password',
  confirmPassword: 'Confirm password',
  iaccept: 'I accept the ',
  termsAndConditions: 'Terms and Conditions ',
  privacyPolicy: ' Privacy Policy',
  Continue: 'Continue',
  alreadyAccount: 'Already have an account? ',
  forgotPassword: 'Forgot password',
  next: 'Next',
  dontHaveAccount: 'Don’t have an account? ',
  registerHere: 'Register here! ',
  resetPassword: 'Reset Password',
  verifyCode: 'Verification code',
  enterVerificationCode: 'Enter verification Code',
  resendCode: 'Resend Code',
  checkEmailForVerification:
    'Please check your email for the verification code',
  enterVerificationCodeToReset:
    'Please enter your verification code to reset your password',
  codeIsInvalid: 'Code is invalid',
  welcomeBack: 'Welcome back',
  welComeBackDescription:
    'Welcome back to InspectReply-AI! Dive back into seamless home inspections with instant insights, accurate cost estimates, and top local contractors ready to help.',
  searchReports: 'Search reports',
  dateCreated: 'Date Created: ',
  totalRepairCost: 'Total Repair Cost: ',
  lastShared: 'Last Shared: ',
  viewFullReport: 'View Full Report',
  noReports: 'No Reports',
  emptyContent: 'Click the + button to add your first report.',
  uploadFile: 'Select here to upload file',
  uploadPdf: 'Click to upload a PDF file.',
  reportGenerated:
    '...and when your report is generated they can be pre-populated.',
  generateReport: 'Generate Report',
  preferredContractor: 'Add Preferred Contractors',
  addReport: 'Add report',
  useContractor: 'Use preferred contractors',
  noteWhenSelected:
    'Note: when selected, this will pull from your top contractors list.',
  needChangePdfNote:
    'Need to make a change? Remove the current report and upload a new one.',
  reportPdfText1:
    'Your report is being generated and may take up to 10 minutes to compile. ',
  reportPdfText2:
    'You will receive a notification once the report is complete.',
  coachMarkText1:
    'This is the report section where you can view all your recent, saved, and shared reports.',
  coachMarkText2: 'Click this to upload a report.',
  coachMarkText3: 'This is the Contractor Section. About this section.',
  gotIt: 'Got it',
};
